apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "kubeflow-icom-cv"
  version: "1.22"
  region: "us-east-1"

vpc:
 id: 

managedNodeGroups:
- name: "kubeflow-icom-cv-mng"
  desiredCapacity: 5
  volumeSize: 100
  instanceType: "m6i.4xlarge"
